sudo: true
dist: trusty
language: cpp
matrix:
  include:
    # Works on Trusty:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # Only do coverage on one configuration
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COVERALLS_CMAKE_OPTIONS='-DDARMA_ENABLE_COVERALLS=On -DDARMA_COVERALLS_UPLOAD=On' && DO_COVERALLS=true"

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz -O /tmp/gtest.tar.gz
  - tar -xvf /tmp/gtest.tar.gz
  - export GTEST=$PWD/googletest-release-1.8.0

install:
  - cd $GTEST
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$GTEST/install -DCMAKE_CXX_COMPILER=$CXX ..
  - make
  - make install

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake -DDARMA_FE_ENABLE_TESTS=On -DCMAKE_CXX_COMPILER=$CXX -DGTEST_DIR=$GTEST/install ${COVERALLS_CMAKE_OPTIONS} ..
  - make VERBOSE=1
  - make VERBOSE=1 test
  - if [ $DO_COVERALLS == true ]; then make coveralls; fi

notifications:
  slack:
    secure: bMpQX03z3t2EKC3E7hi3gOTxE5y6V7Iuc6YKCR19Je8Yq2dWSXmVv0rbOOENs0FT0wnjvm1gbixzbM9sokIPP14SBvufcYm9n+C1nM8XncmDcvzESV7j0C9+C30uNFMRfNwkNx4ua3EgFiZiqeogE21yijRj2RE2i7IVZKbCwQR3d13knTC2hz6M/PTwYGqSmxbptUrQNzrkGIcr/NTCTO5BkuFiSNc1fAghs3kqlExUDhmpKDQPfIzfJz94a/GIBa58pjOvsZoL035IvWBIPa2GLbyeKPpS1hjjXT1bIgeJ3xT6A1+SvQWgr89EFQw/Vz0X7ZjYYX+ZJoLC62QVwCQBQLKYOZp9L/5qh32swDYVGohvJMQTi/1A2bwMkOzgVlU6w7Z7u23vYijY1kT1AG3YBSgQf1igcV6s7kqCokMS5pQR19eyRYV6kIUCR2jL2L5wvlVWFikxdfEHDsEKCw6pNsLDEqtBjgAmcNNkk7k/+8luwms32Irs/hFXugWjCDK36/QcWray6ZgNb3Gx+rZzz9u8Iyp/OYueDSR3eCLNFZe3BkOQvjQfrWXN3zB7LOeBFGPHxykKPnP+8apV/KbTzX/xBZQLOnldjUbyQT7bsuxOXQ5z3xohG0B887o0kig8pLwAFiRmTrVp//CPOuTI8IMt0/if4ncgBlmaDcM=
