This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./sandReportSpec.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file sandReportSpec.acn....done (20 entries accepted, 0 rejected).
Sorting entries....done (85 comparisons).
Generating output file sandReportSpec.acr....done (32 lines written, 0 warnings).
Output written in sandReportSpec.acr.
Transcript written in sandReportSpec.alg.
