
# To use this: give the relative path of the example you want to make.  For instance:
# make examples/hello/hello
# Also, I highly recommend you build with this file in a different directory from the source itself

# Change these...
TOP_SRCDIR ?= /Users/dshollm/Projects/dharma_new/source/head
CXX = /opt/local/bin/g++-mp-4.9

# Should be "mock" or "threads"
# mock is for just getting something that compiles
# threads supports a very primitive and very inefficient working implementation,
# though it's feature support in the spec is likely to lag behind the mock
#DARMA_BACKEND = mock
DARMA_BACKEND = threads

GTEST_SRCDIR=/Users/dshollm/Code/google-test/install/head/clang-3.5_opt
#GTEST_SRCDIR=/Users/dshollm/Code/google-test/source/head
GTEST_LIBDIR=/Users/dshollm/Code/google-test/install/head/clang-3.5_opt/lib

#========================================================================
# Everything below here *should* be fine

MY_BUILDDIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
TOP_BUILDDIR:=$(shell dirname $(shell dirname $(shell dirname $(MY_BUILDDIR))))

CPPFLAGS ?=
CPPFLAGS += -I$(TOP_SRCDIR)/src -I$(TOP_SRCDIR)/mock
CPPFLAGS += -isystem $(GTEST_SRCDIR)/include
CPPFLAGS += -DTEST_BACKEND_INCLUDE="<$(DARMA_BACKEND)_backend.h>"

CXXFLAGS ?= -O0 -g
CXXFLAGS += -std=c++14 -ftemplate-backtrace-limit=0 -pthread

LDFLAGS ?= -L$(GTEST_LIBDIR) -lgtest -lgmock

AR ?= $(shell which ar)
RANLIB ?= $(shell which ranlib)

src2build = $(foreach path,$1,$(patsubst $(TOP_SRCDIR)/%,$(TOP_BUILDDIR)/%,$(path)))
build2src = $(foreach path,$1,$(patsubst $(TOP_BUILDDIR)/%,$(TOP_SRCDIR)/%,$(path)))
striptop = $(foreach pth2,$(foreach path,$1,$(patsubst $(TOP_BUILDDIR)/%,%,$(path))),$(patsubst $(TOP_SRCDIR)/%,%,$(pth2)))
MY_SRCDIR:=$(call build2src, $(MY_BUILDDIR))
stripmine = $(foreach pth2,$(foreach path,$1,$(patsubst $(MY_BUILDDIR)/%,%,$(path))),$(patsubst $(MY_SRCDIR)/%,%,$(pth2)))

MOCK_SOURCES = $(TOP_SRCDIR)/mock/$(DARMA_BACKEND)_backend.cc
MOCK_OBJECTS = $(call src2build,$(MOCK_SOURCES:.cc=.o))
TEST_SOURCES = $(wildcard $(TOP_SRCDIR)/test/gtest/backend/test_*.cc)
TEST_OBJECTS = $(call src2build,$(TEST_SOURCES:.cc=.o))
TEST_EXECS = $(call stripmine,$(TEST_OBJECTS:.o=))
SRCS_REL := $(call stripmine, $(TEST_SOURCES)) ../../../$(call stripmine, $(MOCK_SOURCES))
ALL_OBJECTS := $(MOCK_OBJECTS) $(TEST_OBJECTS)

COMPILE.c = $(CC) $(DEPFLAGS) $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
COMPILE.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
COMPILE.ld = $(CXX) $(DEPFLAGS) $(LDFLAGS) $(CXXFLAGS) $(TARGET_ARCH)
POSTCOMPILE = mv -f $(DEPDIR)/$(call striptop,$*).Td $(DEPDIR)/$(call striptop,$*).d

.PHONY: all clean

all: $(TEST_EXECS)

$(TEST_EXECS): %: $(MY_BUILDDIR)/%.o $(MOCK_OBJECTS)
	$(COMPILE.ld) $(LDFLAGS) $^ -o $@
	dsymutil $@

clean:
	-rm -rf $(ALL_OBJECTS) $(EXAMP_EXECS)

DEPDIR := .d
$(shell mkdir -p $(DEPDIR) >/dev/null)
DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.Td

$(ALL_OBJECTS): $(TOP_BUILDDIR)/%.o : $(TOP_SRCDIR)/%.cc $(DEPDIR)/%.d
	mkdir -p $(dir $@) >/dev/null
	mkdir -p $(DEPDIR)/$(call striptop,$(dir $@)) >/dev/null
	$(COMPILE.cc) $(OUTPUT_OPTION) $<
	$(POSTCOMPILE)

$(DEPDIR)/%.d: ;
.PRECIOUS: $(DEPDIR)/%.d

-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRCS_REL)))

